### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by agolicz** [heatherjzhou/PCAForQTL#3]
Hi,
I just wanted to clarify the data pre-processing steps (they can vary but we were hoping to reproduce the GTEx procedure exactly for input to PCAForQTL).

According to the repo:

`In GTEx’s case, “fully processed” means TPM normalized, filtered, TMM normalized, and inverse normal transformed.`

And according to GTEx website:

```
Gene expression values for all samples from a given tissue were normalized using the following procedure:
- Genes were selected based on expression thresholds of >0.1 TPM in at least 20% of samples and ≥6 reads in at least 20% of samples.
- Expression values were normalized between samples using TMM as implemented in edgeR ([Robinson & Oshlack, Genome 
Biology, 2010 ](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25)).
- For each gene, expression values were normalized across samples using an inverse normal transform.
```

I just want to confirm I understood correctly. The order was:
1. TPM normalization
2. filtering for read count and TPM
3. TMM normalization of TPMs 
4.  Inverse normal transform of TMM normalized TPMs

My questions are:
(i) Did I understand correctly that TMM was performend on TPM values?
(ii) Was there a log transformation at any point of the pre-processing pipeline?

All the best,
Agnieszka

**Comment by heatherjzhou** [comment]
Dear Agnieszka,

I'm sorry I didn't notice your post until now.

I agree with the four steps you summarized. From my understanding, TMM was indeed performed on TPM values, and there was not a log transformation. However, I did not participate in the production of GTEx data and only used their published data, so I cannot guarantee that my understanding is correct. Also, I think the reasonable preprocessing steps can depend on the data and the researcher's perspective, so what GTEx chose to do may not necessarily be ideal for your case (just a thought).

Wishing you good luck,
Heather
