### ISSUE TITLE
Choose K for genotype PCs

### ISSUE THREAD

**Issue by Gongmian784** [heatherjzhou/PCAForQTL#4]
Hi,
I've seen runElbow() and runBE() functions could help us choose K for expression PCs. Can I choose K for genotype PCs by implementing these methods?

Best wishes,
Mian

**Comment by heatherjzhou** [comment]
Hi Mian,

I think that in principle, you could use the same ideas to choose K for genotype PCs. However, in practice, people may use more detailed analysis (see, for example, Section 4.1 of the supplementary materials of https://www.science.org/doi/10.1126/science.aaz1776).

Best,
Heather
